kotekan/kotekan

lib/hsa/hsaPulsarUpdatePhase.cpp, lib/processes/pulsarPostProcess.cpp, lib/testing/gpuBeamformPulsarSimulate.cpp
Critical bug fixes:
- incomplete date math in the pulsar phase calculation (affecting month of January and February) 
- proper truncation of large negative numbers in pulsar post processing
=> Bug in pulsar date math and PP truncation

lib/processes/rawFileRead.cpp, python/kotekan/visbuffer.py
Added the ability to read back GPU buffer dumps in python.
=> Read debug frames

lib/processes/bufferRecv.cpp, lib/processes/bufferSend.cpp
Does not fix #241 but might help debugging it.
=> Print errno in bufferRecv accept connection

lib/processes/applyGains.cpp, lib/processes/applyGains.hpp, lib/processes/visCompression.cpp, lib/processes/visCompression.hpp
=> Balancing with multithreaded recv processes

Jenkinsfile, lib/core/basebandApiManager.cpp
Our MacOS CI server is dying, and we need to remove it from the CI process until we can fix it, or get a new one...
=> Disable MacOS CI builds

lib/processes/computeDualpolPower.cpp, lib/processes/rfiAVXVDIF.cpp
=> another Werror fix: ignore unused parameters

kotekan/kotekan.cpp
Fixes a missing return statement that allowed the `/start` endpoint to try to start a new mode while kotekan was already running. 
Also improves the logging around the `/start`, `/stop`, and `/kill` endpoints.
=> Fix bug in `/start` endpoint, and add more logging

lib/processes/visTestPattern.cpp, tests/test_vistestpattern.py
- Speed up of expected data computation
- Export metrics also for good frames
=> Patterntest fixes after testing

python/kotekan/scripts/ctl.py
Some fixes to make the kotekan_ctl script more usable and installation work better. The timeouts may need to be tweaked, I wasn't sure how long would be needed.
=> Update ctl script

lib/core/basebandApiManager.cpp, lib/core/basebandReadoutManager.hpp, lib/processes/basebandReadout.cpp
This will help us analyze latencies in baseband requesting and processing.
=> Track times of baseband processing steps and return them in the status

config/chime_science_run_gpu.yaml, lib/core/buffer.c, lib/core/buffer.h, lib/dpdk/iceBoardHandler.hpp, lib/hsa/hsaBeamformKernel.cpp, lib/hsa/hsaBeamformOutput.cpp, lib/hsa/hsaBeamformOutput.hpp, lib/hsa/hsaBeamformPulsarOutput.cpp, lib/hsa/hsaBeamformPulsarOutput.hpp, lib/hsa/hsaOutputData.cpp, lib/hsa/hsaOutputData.hpp, lib/hsa/hsaPulsarUpdatePhase.cpp, lib/processes/bufferStatus.cpp, lib/processes/frbPostProcess.cpp, lib/processes/monitorBuffer.cpp, lib/processes/valve.cpp
Dumps more detailed buffer status information when a backup occurs.
=> Better crash logging (part 1)

kotekan/kotekan.cpp, lib/core/buffer.c, lib/core/metadata.c
=> Fixed memory leaks.

lib/core/metadata.c
=> Free container in correct place.

lib/stages/visDebug.cpp, lib/stages/visDebug.hpp, lib/stages/visRawReader.cpp, lib/stages/visRawReader.hpp, python/kotekan/visbuffer.py
This adds the option for limiting the read rate for visRawReader to try
and reduce issues with gossec over NFS. It also adds the ability to
create VisRaw style files from Python space for testing.
=> feat: rate limiting for the visRawReader

lib/core/factory.hpp, lib/utils/CMakeLists.txt, lib/utils/type.cpp, lib/utils/type.hpp
When trying to create a type that is not known, print the name.
=> feat(factory): more verbose exception msg

lib/stages/timeDownsample.cpp, lib/stages/timeDownsample.hpp, lib/stages/visAccumulate.cpp, lib/stages/visAccumulate.hpp, lib/testing/fakeVis.cpp, lib/testing/fakeVis.hpp, tests/test_time_downsample.py
Also, this adds an option to throw away frames that are too old.
=> Accumulate RFI total in timeDownsample

python/kotekan/version.py
* Fix version script bug
* Fix black style
=> Re-merge of develop into master for 2019.10

CMakeLists.txt, lib/stages/applyGains.cpp, lib/stages/applyGains.hpp
<s>Can someone try building this with clang, please?</s>
This doesn't compile with gcc-5.
Closes #569
Closes #568
=> Switch to C++17

Jenkinsfile
Enable the old Jenkins server while we fix the new one.
=> Revert Jenkinsfile

Jenkinsfile
The parallel make commands in the Jenkinsfile take about 2min with this (without any changes to the source files).
Closes #532
=> Use ccache to speed up jenkins build

lib/stages/bufferRecv.cpp, lib/stages/bufferRecv.hpp, tests/conftest.py, tests/test_networkbuffer.py
@cubranic The test I added failed before your changes.
=> Buffer recv conn instance transfer time metric

lib/utils/visFileRaw.cpp
This is so `gossec` user can move and delete files
=> fix(visFileRaw): Make files group-writeable.

lib/hsa/hsaRfiUpdateBadInputs.hpp
Update `hsaRfiUpdateBadInputs` documentation.
=> Updated out of date documentation.

lib/stages/pulsarPostProcess.cpp
=> fix(pulsarPostProcess): build error in recent GCC clang

config/aro_record.yaml
=> New ARO config file changes.

config/chime_science_run_gpu.yaml, config/chime_science_run_recv.yaml
=> fix(config): changed buffer sizes and updated gains/rfi params

lib/hsa/hsaPulsarUpdatePhase.cpp, lib/stages/beamformingPostProcess.cpp, lib/stages/frbPostProcess.cpp, lib/stages/pulsarPostProcess.cpp, lib/testing/pulsarSimProcess.cpp, lib/utils/BranchPrediction.hpp
=> refactor(BranchPrediction): multiple definitions of (un)likely

config/chime_science_run_gpu.yaml, lib/core/configUpdater.cpp, tests/test_receiveflags.py
The key "updatable_config" is now allowed to be higher up in the config
tree. This is more in line with the rest of kotekan's config parsing.
Closes #277
=> feat(configUpdater): improve updatable_config key search

lib/core/Config.cpp, lib/core/Config.hpp, lib/core/StageFactory.cpp, lib/core/StageFactory.hpp, lib/core/bufferFactory.cpp, lib/core/bufferFactory.hpp, lib/core/configUpdater.cpp, lib/core/configUpdater.hpp, lib/core/metadataFactory.cpp, lib/core/metadataFactory.hpp
=> refactor(Config): mark some member functions const

config/chime_science_run_gpu.yaml, config/chime_science_run_gpu_no_output.yaml
=> fix(config): add valve process before RFI flagging in GPU configs

lib/utils/updateQueue.hpp, tests/boost/test_updatequeue.cpp
=> fix(updateQueue): fmt formatter: copy before iterate

tools/docker/Dockerfile
=> ci(docker): set arch to haswell in CFLAGS

python/scripts/rfi_receiver/rfi_receiver.py
Also cleans up the code to make it easier to follow.
=> Fix logic to enable/disable RFI zeroing.

.github/workflows/main.yml, tools/docker/Dockerfile
=> Fix the CI

tests/test_accumulate.py, tools/docker/Dockerfile
=> ci(docker): build bitshuffle with -march=haswell

lib/stages/BaseWriter.hpp
=> Update docs with new metric names.

tools/docker/Dockerfile
(cherry picked from commit dee97cea9459eb327cf75e8841da8e159638790d)
=> ci(docker): bump apt versions to 18.04.3

tools/docker/Dockerfile, tools/iwyu/docker/Dockerfile
This should trigger the rebuild and upload of a "develop"-tagged docker container of each type.
=> ci(docker): change Dockerfiles to trigger rebuild

lib/stages/visRawReader.cpp, lib/stages/visRawReader.hpp, lib/stages/visTranspose.cpp, tests/conftest.py, tests/test_applygains.py, tests/test_transpose.py
Here is the fix for the dataset ID changes not being recorded within a file. There is also an updated unit test that checks this issue specifically. Reverting the fix and running the unit test fails.
Later today I will try and run this version on some of the data we acquired since yesterday and confirm it has resolved the issue.
=> Dataset ID fix

lib/stages/RfiFrameDrop.cpp
There was a typo. Changed lock.release() -> lock.unlock()
release() releases the ownership over the mutex.
=> fix(RfiFrameDrop): mutex can't get acquired on second frame

config/beam_recv_template.yaml, lib/stages/BeamInspect.cpp, lib/stages/BeamInspect.hpp, lib/stages/CMakeLists.txt
Simple stage and config to get people started with writing the extra beam receivers.
=> Extra beam recv config template and testing stage

lib/core/prometheusMetrics.cpp, tests/boost/test_prometheus_metrics.cpp
If they are not, all metrics in a scrape will get dropped.
https://prometheus.io/docs/instrumenting/exposition_formats/
=> fix(prometheusMetrics): ensure NaN and Inf are valid Prometheus formatting

python/kotekan/shared_memory_buffer.py
This is the basic form of the timeout addition. `120` seconds was chosen based on what is the current default config for the kotekan timeout.
Should we also have this be configurable?
If Kotekan is running on a Mac, where `sem_timedwait` is not available, it will revert to the default of "waiting infitnitely".
=> feat(shared_memory): add a timeout while waiting for semaphore

config/chime_science_run_gpu.yaml, config/chime_science_run_gpu_no_output.yaml
@andrerenard this would be a hotfix to mitigate the issues we're seeing.
=> config: increase low sample fraction to mitigate var calculation bugs

lib/stages/visAccumulate.cpp
=> Remove dummy gatingState from frame when dataset ID changes.

docs/sphinx/compiling/general.rst, docs/sphinx/dev/dev_unittests.rst
- Added details for new test files
- Updated cmake option to DWITH_TESTS
=> Update boost test documentation

lib/utils/visUtil.cpp, lib/utils/visUtil.hpp, tests/boost/CMakeLists.txt, tests/boost/test_stat_tracker.cpp
- Deque is used for min and max with O(1) processing time
- Advanced calculation formulas are used for avg and std_dev with O(1) processing time
- Unit tests have been added to test min, max, avg and std_dev
=> Add a statistic tracker for min/max/avg/std

docs/sphinx/compiling/general.rst
Update instructions for installing h5py from source.
=> Update instructions for installing h5py from source.

lib/utils/visUtil.cpp, lib/utils/visUtil.hpp, tests/boost/test_stat_tracker.cpp
- add tracker name
- add tracker unit
- add timestamp
- add brute force min/max
- update unit test
=> Improve stat tracker

tools/debug_tool/static/pipeline_viewer.js
- Read cpu stats from cpu_ult
- Print total cpu usage
- Show usr and sys usages in tooltip
=> Add cpu stats to web interface

tools/debug_tool/static/pipeline_viewer.js, tools/debug_tool/static/styles.css
Add a sidebar to display tracker current info
=> Add sidebar to show trackers_current info
