lib/core/configUpdater.cpp, lib/core/configUpdater.hpp, lib/utils/visUtil.cpp, lib/utils/visUtil.hpp
configUpdater is now more strict about number types and does not accept `float` updates that were of a number type `integer` or `unsigned` before. `integer` and `unsigned` values are allowed to be used to update each other.
=> configUpdater: more strict about number types (#369)

lib/processes/pulsarPostProcess.cpp
- align pulsar vdif packet to %1.6ms instead of %625 samples
- remove fpga_seq_num_low32 from vdif header (to avoid confusion)
=> Psr time offset

lib/processes/visRawReader.cpp, lib/processes/visWriter.cpp, lib/utils/visFileRaw.cpp
Without `throw` these Exceptions were only created, but probably never seen by anyone.
In the case of `visRawReader`, `munmap` could also be moved to the end of `main_thread` (destructors shouldn't throw). 
Replaces #372 with the following additions:
- Pointed at `master` for hotfix
- Catch exception of raw file creation
- raise SIGINT to make sure kotekan is exiting when munmap failes in `~visRawReader`
=> fix missing throw keywords

lib/core/basebandApiManager.cpp, lib/core/basebandApiManager.hpp, lib/processes/basebandReadout.cpp, lib/processes/basebandReadout.hpp
Received requests are counted at the node (kotekan) level by metric
`kotekan_baseband_requests_total`. It has no labels, other than Kotekan's
standard "stage".
Completed requests are tracked by `kotekan_baseband_readout_total`. This is kept
per-stage, and provides two useful labels: "freq_id" provides the stage's
frequency channel, and "status" separates the time series based on the outcome
of the request ("done" if successful, "error" if there was a problem writing the
data, and "no_data" if there was no available baseband data for the requested
time interval.
=> Implement metrics for number of received and completed baseband requests

python/kotekan/runner.py
=> runner.py: use kotekan -c instead of -d

kotekan/kotekan.cpp, python/kotekan/visbuffer.py
Mark numpy dtype labels as ASCII to work with unicode_literals. Only in VisRaw for now. Also made VisRaw work with stacked data.
If this is deemed correct I can go through and fix the other dtypes in the file. Also, it just occurred to me that this could potentially mess things up in Python 3... Any idea?
=> Patch Python2 numpy dtypes to work with the future.unicode_literals import

lib/processes/visCompression.cpp
also adds a label to all its metrics: thread_id
=> frame_id metric for visCompression

lib/core/buffer.c
Yeah, I also thought this was fixed.
=> fix unused variable error for _WIND

config/chime_science_run_recv.yaml
This makes small changes to the receiver config to interface with the ringmap maker on `recv1`.
The list of frequencies I included is just a placeholder that I used for testing, but I will update it shortly with selected frequencies, so please don't merge until then. I just wanted to make sure this is to get this going before the deployment window closes.
=> Update receiver config for ringmaps

lib/processes/visCompression.cpp
the labels where not passed to the metrics, so they are not too useful at the moment
=> add labels to compression metrics

lib/hsa/hsaRfiMaskOutput.cpp, lib/hsa/hsaRfiMaskOutput.hpp, lib/metadata/chimeMetadata.h, lib/processes/visAccumulate.cpp
It's possible that `hsaRfiMaskOutput.cpp` will count packet loss zeroed samples from `zeroSamples.cpp` twice.   This is because first `zeroSamples` adds to the lost samples counter for packet loss, and then later the RFI system might zero out the same samples (but in 256 time sample blocks), leading to double counting.   This fix checks if any of the samples zeroed in `zeroSamples` would be counted twice in `hsaRfiMaskOutput` and corrects for them. 
Also adds a new metadata value for number of RFI flagged samples.
=> Fix double counting of RFI and lost packets

scripts/version.py
Otherwise, `python` has to be v2 for `make` to succeed generating the version step.
=> Make the `version.py` script Python 2/3-compatible

lib/processes/basebandReadout.cpp, lib/processes/basebandReadout.hpp
- name: `kotekan_baseband_readout_in_progress`
- value: 1 if readout is in progress, 0 otherwise
=> Add a metric that indicates if a baseband dump is in progress

config/chime_science_run_gpu.yaml
The FRB and Pulsar post process and networking threads where given only one of the two vCPU cores they were allowed to use.  This seems to have caused some of the system instability, since these stages were using about 95% of their core.   After this change CPU usage between the two cores is about 70%.
=> Fix CPU affinity for FRB/Pulsar stages

lib/processes/basebandReadout.cpp
Otherwise the metric is missing until the node receives a baseband dump request.
=> Initialize `kotekan_baseband_readout_in_progress` to 0 at start of main loop

lib/core/basebandApiManager.cpp, lib/core/basebandApiManager.hpp, lib/core/restServer.cpp, lib/core/restServer.hpp
Adds support for URL query args. e.g. `/my_endpoint?my_option=my_val`
Changes baseband status request API from `/baseband/<event_id>` to `/baseband?event_id=<event_id>`
=> Add support for URL query args

kotekan/kotekan.cpp
Resolves issue #450 by just exiting on config error.  This should be considered a temporary fix until the issues in #464 can be resolved.
=> Exit on config error

lib/utils/osxBindCPU.cpp, lib/utils/osxBindCPU.hpp
This was probably caused by #483, which didn't update this OSX-only file for
changes in the logging API.
=> Fix compile errors in osxBindCPU.cpp

lib/core/Config.cpp
The hash of the JSON serialization was mismatching the Python
implementation of the hash in chime-experiment/coco
Closes #477
Also see https://github.com/chime-experiment/coco/pull/167
=>  Use msgpack for state hasing

CMakeLists.txt
It was disabled because the fmt library was triggering this warning until
version 5.3.0.
=> cmake: Turn on -Wunused-local-typedefs

lib/stages/applyGains.cpp, lib/utils/updateQueue.hpp
This goes against both our code standard and recommended C++ practice.
=> Remove `using namespace std` from a header file (closes #489)

lib/hsa/kernels/CMakeLists.txt
Add missing `DEPENDS` call cmake.
Fixes #429
=> Regenerate hsaco files on changes to .cl files, fixes issue #429

lib/stages/bufferMerge.cpp, lib/stages/receiveFlags.cpp, lib/stages/valve.cpp, lib/stages/visTestPattern.cpp, lib/testing/hexDump.cpp, lib/utils/visUtil.hpp
`fmt::format("{:d}", frame_id)` failed on run time.
Add custom formatter that casts `frameID`s to `int` to fix this.
=> fix(visUtil): add custom fmt formatter for frameID

docs/sphinx/dev/dev_style_guide_code.rst
- files containing classes use `CamelCase`, e.g., `MyClass.hpp`
- files containing standalone functions use `snake_case`, e.g., `net_utils.hpp`
=> Clarify file naming guidelines

lib/core/buffer.c, lib/core/buffer.h
Allow a consumer to "unregister".  This is a requirement for #511 in the `ReadGain` stage, which needs to read the frequency metadata from the first frame of the network input buffer, but doesn't need to read the frames after learning which frequency is being managed by that stream.
=> Add unregister consumer function

lib/dpdk/dpdkCore.cpp, lib/dpdk/iceBoardShuffle.hpp
Checks if the cabling (streamIDs) meets the expected pattern for a correct shuffle.  This should resolve the bug in the last run where the system created duplicate frequency products. 
Closes #487
=> DPDK: Check for correct cabling

lib/stages/visRawReader.cpp, lib/stages/visRawReader.hpp, lib/stages/visTranspose.cpp, lib/utils/datasetState.cpp, lib/utils/datasetState.hpp
This is a hack to record the dataset ID in the archive files. It should be replaced eventually by making `gossec` aware of the dataset broker and using that to communicate metadata.
=> write dataset ID

lib/core/basebandReadoutManager.cpp, lib/core/basebandReadoutManager.hpp, lib/stages/basebandReadout.cpp, lib/stages/basebandReadout.hpp, lib/utils/BipBuffer.cpp, lib/utils/BipBuffer.hpp, lib/utils/CMakeLists.txt, lib/utils/SynchronizedQueue.hpp, tests/boost/CMakeLists.txt, tests/boost/test_bip_buffer.cpp, tests/boost/test_synchronized_queue.cpp, tests/test_baseband_readout.py
Makes baseband dump stages operate in parallel with each other, rather than blocking at each processing step of a single baseband request.
- readout data area is shared by multiple events (as long as there is space), by making it a bipartite circular buffer (BipBuffer)
- the readout thread has a queue of requests `waiting` to be processed, and reads out their baseband data into a segment of the BipBuffer if there is one available. (If there isn't, the request is errored-out and the thread moves on to the next request in its queue.)
- when the readout thread is done with a requests, it adds it to the writeout thread's `ready` queue. This request includes the pointer to the request's data in the BipBuffer.
- the writeout thread processes requests in the `ready` queue, creating the HDF file …
=> Redesign of baseband processing flow and synchronization (fixes #497)

config/chime_science_run_gpu.yaml
Internally the baseband buffer allocated `2 * max_dump_samples`, so this is actually keeping it the same size after the changes in #497
=> Reduce baseband dump buffer size.

config/chime_science_run_gpu.yaml, config/chime_science_run_gpu_no_output.yaml
We need to have a testing config that won't interact with the rest of the system when running on the test nodes.   The diff for that config looks like this: 
```
$ diff chime_science_run_gpu.yaml chime_science_run_gpu_no_output.yaml 
82c82
<   use_dataset_broker: True
---
>   use_dataset_broker: False
754c754
<     kotekan_stage: frbNetworkProcess
---
>     #kotekan_stage: frbNetworkProcess
1056c1056
<     kotekan_stage: pulsarNetworkProcess
---
>     #kotekan_stage: pulsarNetworkProcess
1240c1240
<     kotekan_stage: bufferSend
---
>     #kotekan_stage: bufferSend
1244c1244
<     kotekan_stage: bufferSend
---
>     #kotekan_stage: bufferSend
1248c1248
<     kotekan_stage: bufferSend
---
>     #kotekan_stage: bufferSend
1260c1260
<     kotekan_stage: rfiBroadcast
---
>     #kotekan_stage: …
```
=> Add a "no output" config, and cleanup GPU config

CMakeLists.txt, include/CMakeLists.txt, kotekan/CMakeLists.txt, kotekan/kotekan.cpp, lib/CMakeLists.txt, lib/core/CMakeLists.txt, lib/gpu/CMakeLists.txt, lib/hcc/CMakeLists.txt, lib/hsa/CMakeLists.txt, lib/metadata/CMakeLists.txt, lib/opencl/CMakeLists.txt, lib/testing/CMakeLists.txt, lib/utils/CMakeLists.txt
Fixes linking errors on macOS Catalina due to completely empty libraries being present, and fixes an issue when yamllint isn't present when using Python 3.
=> macOS link fix

tests/boost/dataset_broker_consumer.cpp, tests/boost/dataset_broker_producer.cpp, tests/boost/dataset_broker_producer2.cpp
boost required "--" before command line arguments that are passed into
the test, but they stopped requiring this apparently. So now we can
handle both cases.
=> test(dataset_broker): ignore argv[1]=="--"

config/chime_science_run_gpu.yaml, lib/hsa/hsaRfiUpdateBadInputs.cpp, lib/hsa/hsaRfiUpdateBadInputs.hpp, lib/stages/CMakeLists.txt, lib/stages/bufferBadInputs.cpp, lib/stages/bufferBadInputs.hpp
Buffers updates to the bad input list, which is fed to the hsaRfiUpdateBadInputs command object.
Fixes a bug where two consecutive updates to the bad input list in <0.5s would result in the second update being lost. The bug was found as a result of investigating #594.
Also applies a fix for the race condition found in #600 which closes #594
Co-authored-by: andrerenard <andre@renard.io>
(cherry picked from commit b5fd669d89947a4a02bccfd4f942c736ac952d98)
=> Fix RFI bad inputs update problems

lib/hsa/hsaAsyncCopyGain.cpp, lib/hsa/hsaAsyncCopyGain.hpp
It looks like the FRB gain update code had a similar race condition to the RFI bad_inputs list update problems.  Given the nature of FRB gains and their effect on the data, it's entirely possible this was just never noticed.
=> Fix possible race condition in FRB gain updates.

lib/stages/frbNetworkProcess.cpp, lib/stages/frbNetworkProcess.hpp, lib/utils/CMakeLists.txt, lib/utils/network_functions.cpp, lib/utils/network_functions.hpp
Add checks for FRB destination liveness and deactivation of destinations:
- add a background thread that periodically pings every FRB destination and
keeps track of how recently they've replied
- nodes that have gone too long without replying are marked dead and packets
aren't sent to them until they start responding to pings again
- "deactivate" sending a beam to an L1 destination by having the destination IP as an empty string in the Kotekan config.
- add a REST API that allows "deactivating" a destination. Such destinations
will still be pinged, but packets won't be sent to them until they are
activated again
- the API works by POSTing to URL `/frb/update_destination` a dictionary with
keys "host" (a string that must exist as an element in `L1_node_ips` config
entry), and "active" (a …
=> Detect missing/dead FRB nodes (closes #449)

lib/stages/frbPostProcess.cpp, lib/stages/frbPostProcess.hpp
- add a Prometheus metric to count masked FRB packets
- check for lost FPGA samples *after* syncing inputs
=> Count masked FRB packets

lib/stages/frbPostProcess.cpp
The frbPostProcess system was looking for flags to say if the packet was lost 16x past the end of the array because of an indexing error.   This error appears to have been added in #438, but was never noticed.
=> Fix index error in frbPostProcess

config/chime_science_run_gpu.yaml, config/chime_science_run_gpu_no_output.yaml, lib/stages/frbNetworkProcess.cpp, lib/stages/frbNetworkProcess.hpp
We are seeing recurring storms of nodes marking multiple destinations dead and
then live again within a few seconds, so it's clear either there is a bug in the
current implementation or the thresholds need to be fine-tuned. Since we are
pressed to start the run, it makes sense to add a way to disable this feature
from the configuration, should we want to do so without reverting it completely.
=> Disable the L1 destination checking if `ping_dead_threshold` is 0

tests/boost/CMakeLists.txt, tests/boost/dataset_broker_consumer.cpp, tests/boost/dataset_broker_producer.cpp, tests/boost/dataset_broker_producer2.cpp
I removed the linker dependency of kotekan_libs for the comet tests, to speed up building those on comet's travis CI. But this should also speed up the linking here a little bit. Note that I tried and failed doing the same for the other boost tests. I looks like there are some bugs in the cmake configuration for kotekan_core / buffer.c.
=> Clean up boost test cmake dependencies

lib/stages/basebandReadout.cpp
Because `BasebandApiManager` is not a Stage, we don't have access to the running
configuration to construct the destination relative to `base_dir`, so the error
handling has to be done in the BasebandReadout. This is a little less ideal,
because this way we can't respond with an HTTP error as part of the request, but
still prevents using up the time to read out the samples that cannot be saved to
the requested destination.
=> Check for baseband destination directory before reading out the samples (#640)

lib/stages/RfiFrameDrop.cpp, lib/stages/RfiFrameDrop.hpp
Allows much shorter mutex protected section in main thread.
Closes #638
=> refactor(RfiFrameDrop): shared_ptr instead of copy updates

lib/stages/bufferRecv.hpp
- make most member functions of bufferRecv private
- add connInstance as a friend so it can still use them
Closes #623
=> refactor(bufferRecv): make member functions private

lib/hsa/hsaPulsarUpdatePhase.cpp
* Clamp a variable which was resulting in `NAN` in the case of a static pointing
* Disable tracking for beams with when `scaling == 1`
=> Pulsar gain calculation hotfix for 26m passthrough

config/chime_science_run_gpu.yaml, config/chime_science_run_gpu_no_output.yaml
(Note that this is based off `master`, in case we want to deploy it as a quick fix during February power shutdown.)
=> Fix #667: use the right name for "dead_ping_threshold" in the config

.github/workflows/main.yml, CMakeLists.txt, LICENSE, cmake/FindLAPACKE.cmake, lib/core/buffer.c, lib/core/configUpdater.cpp, lib/core/configUpdater.hpp, lib/stages/CMakeLists.txt, tests/test_baseband_readout.py, tests/test_dataset_broker.py, tests/test_freqslicer_broker.py, tests/test_networkbuffer.py, tools/docker/Dockerfile, tools/docker/README.md, tools/iwyu/docker/Dockerfile
Okay this is ready to go. @andrerenard I had to add a few options to the build scripts to make it all work: one to disable mlocking the buffer memory; and one to explicitly set the build architecture, so it would be great if you could look at those. @nritsche if you could check everything else.
Once this is reviewed and merged, I think we can just change the Jenkins webhook status to inactive and it will stop reporting.
There's a few things it doesn't yet do, which we should address in subsequent changes:
- The baseband readout tests are disabled as they didn't work trivially
- All of the tests involving comet are disabled. This should be easy to fix, probably by just installing redis into the container.
- It doesn't built the docs
- It doesn't do a full CHIME kotekan build because of …
=> Run CI on Github actions

.github/workflows/main.yml, tools/iwyu/docker/iwyu.sh
The iqyu action broke in #699 and is fixed here:
- restore iwyu cmake options
- add path (..) to cmake command
- fix path to iwyu.sh
- iwyu.sh: fix path to project .imp
=> ci(github): fix iwyu action

config/chime_science_run_gpu.yaml, config/chime_science_run_gpu_no_output.yaml, lib/stages/bufferSend.cpp
Also sets the log level for HFB send to `error` since we don't expect to have a full time HFB receiver in this run.
=> Adjust log levels in bufferSend

.github/workflows/main.yml, tools/docker/Dockerfile
Closes #730 
Do an `apt-get update` every time we use `apt-get install`.
Also chops the build_docker step into 4 steps so the output is easier to read and removes the pipes in the docker_build steps commands because they lead to the exit codes being ignored.
=> ci(github): repair docker_build step

.github/workflows/main.yml, CMakeLists.txt, README.md, docs/sphinx/compiling/general.rst, lib/dpdk/iceBoardShuffle.hpp, lib/stages/RingMapMaker.hpp
Adds 2 builds to github action CI:
- full CHIME build using clang
- macOS build outside of dockerimage: slower because needs to install stuff
- takes 15min with an empty ccache
- and 4min after ccache has been filled
This is the compiler the mac build uses:
```
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - works
```
Let me know if that's what we want.
=> Clang and MacOS CI builds

config/chime_science_run_recv.yaml, lib/utils/updateQueue.hpp, tests/boost/test_updatequeue.cpp
PR is against master!
Was at default (5), which allows frames to arrive 50s late when
calbroker sends 1 update in 10s and 150s late when flagging broker sends 1
update in 30s. Increase to num_kept_updates=24 to allow frames 240s late
for gain updates and 720s late for flagging update.
Additionally fixes a bug that is currently worked around by a log level change inserted into the running config. The fix (#727 ) was merged into develop previously.
=> hotfix - fix(receiver config): increase num kept gain/flags updates

lib/stages/ReadGain.cpp, lib/stages/ReadGain.hpp
This PR adds two metrics for the ReadGain stage:
- `kotekan_gains_last_update_success` is a 0/1 flag to indicate the success of last update (1 means the gains files were read successfully and sent down the pipeline)
- `kotekan_gains_last_update_timestamp` records the timestamp of the last update, whether it successfully read the gains files or had to apply the default gains. ("Time" here means the current time when the update was applied, not the time it was generated by the calibration broker.)
Both metrics include a label `type` with values "frb" and "pulsar", to keep their respective updates separate.
=> Track the time and success of gain updates (fix #687)

config/chime_science_run_recv.yaml, lib/stages/applyGains.cpp, lib/stages/applyGains.hpp, tests/test_applygains.py
If the gain update does not require a dataset ID, this will use the current one. Fixes #740 .
=> Check if the new gain update requires a new dataset ID. 

config/chime_science_run_gpu.yaml, config/chime_science_run_gpu_no_output.yaml
For some completely inexplicable reason, coco has decided that the value of `tol_eval` is not the floating point `0.00001` but is the string `"1e-05"`. It didn't used to, this is a recent decision it's made, I can only presume it missed lunch yesterday and got angry, because this only started to happen when the correlator came back online at 4pm yesterday.
Now you'd think this would be a big issue, right? After all the `EigenVisIter` process knows it's expecting a `double` and there's no way of converting a JSON string to a float, so it should just error out. Oh, but there is! Don't you remember the ridiculous in built arithmetic expression parsing logic that will attempt to turn any string into an arithmetic type? Indeed, it sees that string, ignores the fact it's scientific notation, …
=> config: change to explicit notation to avoid config parsing issues

lib/core/Config.hpp, lib/stages/pulsarPostProcess.cpp, python/kotekan/runner.py, tests/boost/test_config.cpp
This change adds the following fixes:
- Check for unexpected tokens after exp()
- Allow isNumber regex to parse numbers in scientific notation
- Variable regex now accepts single characters so they don't get dropped from the token list
- Throw exception for incomplete expressions (i.e. `5 + `). 
Closes: #378
=> Fix configEval parsing issues

python/kotekan/runner.py, tests/test_accumulate.py, tools/docker/Dockerfile
This is an attempt to fix the failing pytests:
- bump pytest to version 6.0.1 fixes the problem we had:
```
scheduling tests via LoadFileScheduling
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.7/dist-packages/_pytest/main.py", line 196, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.7/dist-packages/_pytest/main.py", line 240, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.7/dist-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/dist-packages/pluggy/manager.py", …
```
=> Fix failing pytests

lib/dpdk/invalidateVDIFframes.cpp, lib/dpdk/invalidateVDIFframes.hpp
* Adds the metric `kotekan_vdif_lost_frames_total` to track VDIF frames lost to bad input packets.
=> Add metric to track invalidated VDIF frames

.gitignore, config/aro_record.yaml, config/chime_science_run_gpu.yaml, config/chime_science_run_gpu_no_output.yaml, config/chime_science_run_recv.yaml, kotekan/kotekan.cpp, lib/dpdk/iceBoardVDIF.hpp, lib/hsa/kernels/N2.isa, lib/utils/CHIMETelescope.cpp, lib/utils/CHIMETelescope.hpp, lib/utils/ICETelescope.cpp, lib/utils/ICETelescope.hpp, lib/utils/Telescope.cpp
* Add default frequency mapping for different ICETelescope layouts
* Move query of GPS time to telescope object (and C++ instead of Python)
* Remove CHIME specific GPS references from `kotekan.cpp`
* Allow system to query the FPGA frequency map directly from fpga_master (for testing)
* Change telescope names to match class names (inline with other `kotekan` factory generated objects`)
* (Also sneaks in a change for .gitignore) 
* Adds the metric `kotekan_vdif_lost_frames_total` to track VDIF frames lost to bad input packets.
=> Update Telescope objects

python/kotekan/shared_memory_buffer.py
If kotekan-calbuffer is restarted, then it will write the buffer to a
new location in shared memory, but the calibration broker will continue
to check old location, and will continue to see the same old data, which
it will ignore.
The SharedMemoryReader should check on every .update() call to
see if the file descriptor still has any links.
mmap does not contain a reference to the file descriptor used to create
it, and so we will need to keep the original file descriptor around.
Addresses https://github.com/chime-experiment/ch_cal/issues/2
=> fix(shared_memory_buffer): upon update, first check if link still exists to shared_mem

tools/docker/Dockerfile
In the CI run of #826 the docker image was rebuilt because the base image had a new release. One of the previously version-frozen apt packages was not available anymore and the build failed. To make the version-freezing work, this also freezes the version of the docker base image.
=> ci(docker): freeze base image at rocm/dev-ubuntu-18.04:3.7

lib/hsa/kernels/CMakeLists.txt
A partly rename of the variable inCL_FILEs by cmake-format broke this
cmake file.
=> build(cmake): hsa kernels not generated: variable partly renamed

lib/stages/frbPostProcess.cpp
Multiplying by `1e9` causes a silent cast to float, and then back to an int,
causing the rounding. This fix makes sure we multiply by an integer constant.
=> Fix unintentional rounding when calculating fpga0 timestamp

lib/stages/frbPostProcess.cpp, lib/stages/pulsarPostProcess.cpp, lib/utils/pulsar_functions.hpp
@andrerenard i made a small change to propagate node-ID info down to the backend, which i forgot to make beforehand. it's been confirmed that the backend get's the right frequency labels, but this new `station_id` has been intended to be used for buffering data on the backend during an observation; again, i just forgot to make this change, my mistake.
=> redefinition of station_id attribute for pulsar header

.github/workflows/main.yml, lib/utils/LinearAlgebra.hpp, tools/docker/Dockerfile
When running on site with blaze version `v3.8-12-gf36b481f2` we discovered a regression in the performance of the eigenvalue decomposition.   This change reverts to the `v3.4` API and locks the version in the CI server. 
Also locks `h5py` to `2.9.0` since that broke while I was doing this PR.
=> Revert blaze version to v3.4

lib/dpdk/CMakeLists.txt
It appears that some versions of `cmake` are particular about `library` vs `package`.   This should work in all versions.
=> Switch to find_package for DPDK

.github/workflows/main.yml
- The name of the environment variable `GITHUB_EVENT` was wrong (should be `GITHUB_EVENT_NAME`), so it always tried to get the branch name in the way to do it in a PR. It then also did it that way when `GITHUB_EVENT_NAME` was `push` and we ended up with a branch name `''`. So it never pushed the docker container with the tag `develop`.
- The fallback tag name had to be set actually, not just echo'd
=> Fix docker CI / branches

.github/workflows/main.yml
This is so we stay with clang 9 (see https://github.com/kiyo-masui/bitshuffle/issues/88).
github just bumped their clang version and that broke bitshuffle's build. This installs an older clang version manually.
=> ci(github): fix macos container to 10.14

config/tests/chime_frb_verification.yaml, lib/hsa/hsaBeamformHFBSum.cpp, lib/hsa/kernels/sum_hfb.cl
I was only checking every 4th element of `compressed_lost_samples_buf` on whether to include the sample in the sum.
=> Correctly mask lost samples in sum_hfb kernel.

lib/stages/RfiFrameDrop.cpp
If the `enable` endpoint is called befor the `threshold`-one, an uninitialized state_ptr is accessed -> segfault.
Fix: The `enable` endpoint callback uses an empty vector if the state is not available yet.
I would have preferred to create an initial dummy dataset state in the constructor, but it would have to life in the datasetManager and get registered with comet.
=> Fix RFIFrameDrop dataset state registration

lib/stages/RingMapMaker.cpp, lib/stages/RingMapMaker.hpp
Implement the fingerprint mechanism from VisCompression to handle
frequently changing dataset IDs without regenerating products
unnecessarily.
I haven't tested this because it's not straightforward to reproduce the environment it is meant to run in, so we should find a time during the deployment to try it out. 
In the meantime, if someone else could look through the dataset state logic that would be great, since it never fails to confuse me.
Solves chime-experiment/RTPipeline#93.
=> fix(RingMapMaker, RedundantStack): Improve handling of datasets.

lib/core/basebandReadoutManager.cpp
Baseband API manager needs to acquire a lock on the request currently processed
by either the readout or the writeout thread, in order to see it in a consistent
state. For the endpoint returning only a single event's status, the manager does
not need to acquire this lock if the readout/writeout threads are not processing
this particular event.
=> Remove redundant baseband status locking

lib/stages/visRawReader.cpp
If this is not done, the file will still remain in memory, potentially slowing down other operations
which need to acquire memory.
=> fix(visRawReader): clear the page cache as well as the memory map

lib/stages/ReadGain.cpp, lib/stages/ReadGain.hpp
Fixes a logical error introduced by #811.  Basically the code implicitly required all the beams to be updated every time, but #811 changed it so only one beam was updated and the values of the other beams were just whatever was currently in that frame.  Because of the fact there are 10 beams, the buffer depth for the gains was 5, and all gains are loaded at once on startup, this caused the issue to get mostly hidden - the system just ended up using old gains for some beams. 
The hotfix corrects this by keeping a local set of gains and copying them into each new output frame.  
Closes #935
=> Fix problem with tracking beam gain updates

lib/stages/visAccumulate.cpp
Should we also copy over `rfi_total`?
=> Count all frames in gated datasets

config/chime_science_run_gpu.yaml, config/chime_science_run_gpu_no_output.yaml, lib/hsa/hsaTrackingUpdatePhase.cpp, lib/hsa/hsaTrackingUpdatePhase.hpp
* Moves the instrument latitude and longitude from define constants into the configuration file. 
* Fixes an issue were a `float` was read as an `int`
* Updates the CHIME phase center to the correct location (appears to have been set to the Pathfinder location)
=> Fix phase center for CHIME tracking beamformer

lib/core/restServer.cpp, lib/stages/bufferRecv.cpp, lib/utils/restClient.cpp, lib/utils/restClient.hpp
* Fixes an issue where if libevent picked `select` as its backend API, we would be limited 1024 file handles.
=> Exclude 'select' as a backend API for libevent

CMakeLists.txt, lib/core/CMakeLists.txt, lib/core/Stage.cpp, lib/core/Stage.hpp, lib/core/cpuMonitor.cpp, lib/core/cpuMonitor.hpp, lib/core/kotekanMode.cpp, lib/core/kotekanMode.hpp
New object: CpuMonitor
- Run in a new thread to keep tracking stage CPU usage periodically
- Add a new endpoint /cpu_ult to get the CPU usage message
- Enable CPU monitor by config file
- Only support Linux
- Start CPU monitor from kotekanMode
- Read thread lists from Stages passed by kotekanMode
=> Create a new object to track CPU usage per stage

kotekan/kotekan.cpp, lib/core/kotekanMode.cpp, lib/core/kotekanMode.hpp, lib/core/kotekanTrackers.cpp, lib/core/kotekanTrackers.hpp, lib/stages/testDataGen.cpp
The dump file from `KotekanTrackers` needs the data about the buffers in order to generate the pipeline graph.   This PR adds this feature.  The dump file now contains two JSON objects in the root JSON object called `buffers` and `trackers`.
For example this is a simple JSON dump file with this change:
```
{
"buffers":{
"example_buffer":{
"consumers":{
"/screen_dump":{
"last_frame_acquired":1,
"last_frame_released":1,
"marked_frame_empty":[
0,
0,
0,
0,
0,
0,
0,
0,
0,
0
]
}
},
"frame_size":128,
"frames":[
0,
0,
0,
0,
0,
0,
0,
0,
0,
0
],
"last_frame_arrival_time":1629399352.481672,
"num_frames":10,
"num_full_frame":0,
"producers":{
"/data_gen":{
"last_frame_acquired":1,
"last_frame_released":1,
"marked_frame_empty":[
0,
0,
0,
0,
0,
0,
0,
0,
0,
0
]
}
},
"type":"standard"
}
},
"trackers":{ …
```
=> Include buffer json data with tracker dump file

lib/stages/visAccumulate.cpp, lib/utils/ICETelescope.cpp
Also fixes an issue where the ICETelescope object didn't correctly return the `gps_time_enabled()` value correctly.
=> Fallback to system time if GPS time is not set
